config/routes.rb
Rails.application.routes.draw do
  get 'sam/index'

  get 'titi/index'

  get 'accueil/index'
  match 'accueil', to: "accueil/index", via:[:get]

  root 'accueil#index'

end

app/controllers/accueil_controller.rb
class AccueilController < ApplicationController
  def index
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sam_controller.rb
class SamController < ApplicationController
  def index
    render layout: 'sam'
  end
end

app/controllers/titi_controller.rb
class TitiController < ApplicationController
  def index
  end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sam_helper.rb
module SamHelper
end

app/helpers/titi_helper.rb
module TitiHelper
end

app/views/accueil/index.html.erb
<h2>L'image du jour<small><i class="navbar-right">26/04/17</i></small></h2>
<hr />
<p><img  class="img-responsive center-block cards" src="/img/lolcats/lolcatsdance.jpg" /></p>


<h2>L'image du jour<small><i class="navbar-right">25/04/17</i></small></h2>
<hr />
<p><img  class="img-responsive center-block img-rounded cards" src="/img/lolcats/LOLcat - Shaolin Paws.jpg" /></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bootstrap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- Important! permet le responsive pour mobile -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> --> <!-- test pour les glyphicons, ils ne sont pas dans les fichiers css de bootstrap par défaut -->

</head>
<body>
	<div class="container-fluid">
		<nav class="navbar navbar-inverse">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <i class="navbar-brand">Essai bootstrap</i>
		    </div>
		    <ul class="nav navbar-nav">
		      <li class="active"><%= link_to 'Home', accueil_index_path %></a></li>
		      <li><%= link_to ' Sam', sam_index_path, class: "glyphicon glyphicon-tree-conifer" %></li>
		      <li><%= link_to ' Titi', titi_index_path, class: "glyphicon glyphicon-music" %></li>
		    </ul>
		  </div>
		</nav>
		
		<div class="container-fluid text-center">    
		  <div class="row content">
		    <div class="col-md-3 col-lg-2 sidenav">
		      <p><a href="#">Link</a></p>
		      <p><a href="#">Link</a></p>
		      <p><a href="#">Link</a></p>
		    </div>
		    <div class="col-sm-8 col-lg-9 text-left"> 
		      <%= yield %>
		      <hr />
		    </div>
		  </div>
		</div>
		
		<footer class="container-fluid text-center">
		  <p>Footer Text</p>
		</footer>
	
	</div>

</body>
</html>

app/views/layouts/sam.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bootstrap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- Important! permet le responsive pour mobile -->


</head>
<body>
	<nav class="navbar navbar-inverse">
	    <div class="navbar-header">
	      <i class="navbar-brand">Essai bootstrap</i>
	        <!-- icone menu -->	
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar1">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          <span class="visible-xs navbar-brand">Menu</span>
	        </div>
	        <!-- icone menu -->	

	    </div>
	    <ul class="nav navbar-nav collapse navbar1">
	      <li class="active"><%= link_to 'Home', accueil_index_path %></a></li>
	      <li><%= link_to ' Sam', sam_index_path, class: "glyphicon glyphicon-tree-conifer" %></li>
	      <li><%= link_to ' Titi', titi_index_path, class: "glyphicon glyphicon-music" %></li>
	    </ul>
	</nav>
	
	<div class="container-fluid text-center">    
	  <div class="row content">
	    <div class="col-md-2 col-lg-1">
	    	
	    	
			<div class="sidebar-nav">
			      <div class="navbar navbar-default" role="navigation">
			        <!-- icone menu -->	
			        <div class="navbar-header">
			          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
			            <span class="sr-only">Toggle navigation</span>
			            <span class="icon-bar"></span>
			            <span class="icon-bar"></span>
			            <span class="icon-bar"></span>
			          </button>
			          <span class="visible-xs navbar-brand">Menu</span>
			        </div>
			        <!-- icone menu -->	

			        <div class="navbar-collapse collapse sidebar-navbar-collapse">
			          <ul class="nav navbar-nav">
			            <li class="active"><a href="#">Menu Item 1</a></li>
			            <li><a href="#">Menu Item 2</a></li>
			            <li class="dropdown">
			              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
			              <ul class="dropdown-menu">
			                <li><a href="#">Action</a></li>
			                <li><a href="#">Another action</a></li>
			                <li><a href="#">Something else here</a></li>
			                <li class="divider"></li>
			                <li class="dropdown-header">Nav header</li>
			                <li><a href="#">Separated link</a></li>
			                <li><a href="#">One more separated link</a></li>
			              </ul>
			            </li>
			            <li><a href="#">Menu Item 4</a></li>
			            <li><a href="#">Reviews <span class="badge">1,118</span></a></li>
			          </ul>
			        </div><!--/.nav-collapse -->
			      </div>
		      </div>
		      
		      
	    </div>
	    <div class="col-md-8 col-lg-10 text-left"> 
	      <%= yield %>
	      <hr>
	      <h3>Test</h3>
	      <p>Lorem ipsum...</p>
	    </div>
	    <div class="col-md-2 col-lg-1 sidenav">
	      <p><a href="#">Link</a></p>
	      <p><a href="#">Link</a></p>
	      <p><a href="#">Link</a></p>
	    </div>
	    </div>
	  </div>
	</div>
	
	<footer class="container-fluid text-center">
	  <p>Footer Text</p>
	</footer>
	
	

</body>
</html>

app/views/sam/index.html.erb
<h1>Sam#index</h1>
<p>Find me in app/views/sam/index.html.erb</p>

app/views/titi/index.html.erb
<h1>Le relais! <small class="bg-info">(le titre qui sent bon le parking des routiers)</small></h1>
<hr />

<p class="well well-sm well-lg w3-dark-gray">Petits pas synchronisés :</p>
<video width="400" controls="controls" class="center-block img-responsive">
	<source src="http://i.imgur.com/09LwOEU.mp4" type="video/mp4" /></source>
</video>
<br />
	
<p class="well well-sm well-lg w3-dark-gray">Essaie encore ^^</p>
<video height="400" controls="controls" class="center-block img-responsive">
	<source src="http://i.imgur.com/sEvvy0f.mp4" type="video/mp4"></source>
</video>
<br />